# Generated by Django 5.2 on 2025-05-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('top_text', models.CharField(blank=True, max_length=100)),
                ('bottom_text', models.CharField(blank=True, max_length=100)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
